### ISSUE TITLE
Dev requirements look weird to me

### ISSUE THREAD

**Issue by stof** [blackfireio/player#10]
The console component is listed as a dev requirement, while it is required to have it in the phar (same for other dev requirements btw). This would make them normal requirements

**Comment by fabpot** [comment]
fixed

**Comment by stof** [comment]
This does not seem to be fixed to me

**Comment by xabbuh** [comment]
@stof I can see it: https://github.com/blackfireio/player/blob/master/composer.json#L24 But the commit might be pushed only recently while being older.

**Comment by stof** [comment]
@xabbuh yeah, it was not synchronized from the private repo to here yet
