### ISSUE TITLE
Laravel integration

### ISSUE THREAD

**Issue by absalomedia** [blackfireio/player#26]
Trying to install this via Composer into Laravel 5.2 results in:

>  [InvalidArgumentException]
  Could not find package blackfireioplayer at any version for your minimum-st
  ability (stable). Check the package spelling or your minimum-stability

Are you able to get the Blackfire Player to a stable state inside Composer?

**Comment by xabbuh** [comment]
@absalomedia You can install the package with Composer. What exactly did you try?

**Comment by absalomedia** [comment]
@xabbuh tried `composer install blackfireio/player` on a mostly vanilla Laravel 5.2 build running under a WAMP virtual host setup & ended up with the error I gave you.

**Comment by xabbuh** [comment]
@absalomedia The name of the package is `blackfire/player`: https://github.com/blackfireio/player/blob/master/composer.json#L2

**Comment by absalomedia** [comment]
Sorry for obvious typo.
