### ISSUE TITLE
Cannot access to JSON keys named `@id`

### ISSUE THREAD

**Issue by dunglas** [blackfireio/player#36]
I try to add Blackfire Player to the demo of API Platform: https://github.com/api-platform/demo/pull/91
It looks like it's not possible to access JSON keys containing a special char like `@` (used by JSON-LD).

Example
```
scenario
    visit url('/books')
        name "Post a new book"
        method "POST"
        header "accept: application/ld+json"
        header "content-type: application/ld+json"
        body
        """
        {
          "isbn": "978-2-918390-36-7",
          "title": "Code performance explained",
          "description": "Blackfire.io, the book",
          "author": "Fabien Potencier",
          "publicationDate": "today"
        }
        """
        expect status_code() == 201
        set id json("'@id'")

    visit url(id)
        expect status_code() == 200
```

It looks valid according to JMESPath, but it returns an empty string with BlackFire player. However, accessing to `hydra:member` (the colon is also a special char) works.

**Comment by aaa2000** [comment]
Should work with `set id json('"@id"')`

**Comment by iamluc** [comment]
Thanks @aaa2000 for the hint. 

Yes it looks like the correct behavior bevcause the `json()` method accepts JMESPath. 
@dunglas You can test at http://jmespath.org/tutorial.html#basic-expressions

**Comment by dunglas** [comment]
It works. Thank you very much @dunglas
