### ISSUE TITLE
Profile a Single Page app using Cypress.io or similar

### ISSUE THREAD

**Issue by amenk** [blackfireio/player#44]
We are searching a way to profile frontend scenarios in a ZendFramework2 + ExtJs based app.

As far as I understand the blackfire.io player it works on a HTTP request level.

My idea is as follows:

Write a frontend test suite (cypress.io or Selenium) which is run with blackfire profiler turned on.

How can this be accomplished? Blackfire profiler seems to be kicked of using cryptographic challenges?

* do we have to install the blackfire IO plugin in the cypress.io session?
* Is  there any other way to kick of the profiling in the test-session, for example with a simple Cookie?

**Comment by romainneutron** [comment]
Hello,

There's no current support for cypress.io. However, you can create profiles during your test suite by manually instrumenting your code and use a HTTP header.
You can get inspiration from our documentation that refers to postman to achieve this, see https://blackfire.io/docs/cookbooks/profiling-postman
