### ISSUE TITLE
Make the installation secure

### ISSUE THREAD

**Issue by amenk** [blackfireio/player#45]
Make the installation https://blackfire.io/docs/player/index secure.

* it's not using https://
* no signature check

I suggest you look at the phive project and sign the releases so they can be installed via phive.
If you have questions, I am happy to assist.

**Comment by romainneutron** [comment]
Hello, 

Actually, blackfire.io and all subdomains uses HSTS, so all http traffic is automatically routed from http to https at browser or server level.
However, I've fixed the documentation so no doubt can remain.

**Comment by amenk** [comment]
the HSTS thing does not seem to work - at least with wget

	$ wget http://get.blackfire.io/blackfire-player.phar
	--2019-03-18 14:16:52--  http://get.blackfire.io/blackfire-player.phar
	Resolving get.blackfire.io (get.blackfire.io)... 13.32.223.146, 13.32.223.33, 13.32.223.144, ...
	Connecting to get.blackfire.io (get.blackfire.io)|13.32.223.146|:80... connected.
	HTTP request sent, awaiting response... 200 OK
	Length: 11818822 (11M) [binary/octet-stream]
	Saving to: ‘blackfire-player.phar’

	blackfire-player.ph 100%[===================>]  11,27M  8,41MB/s    in 1,3s    

	2019-03-18 14:16:54 (8,41 MB/s) - ‘blackfire-player.phar’ saved [11818822/11818822]


I guess the doc-update is stuck in some cache? Cause on https://blackfire.io/docs/player/index it says still http://

**Comment by arderyp** [comment]
I'm wondering if the issue I'm seeing with blackfire's non-verifiable yum key is related:

```
Importing GPG key 0xEBFF1218:
 Userid: "packagecloud ops (production key) <ops@packagecloud.io>"
 From  : https://packagecloud.io/gpg.key
http://packages.blackfire.io/fedora/6/x86_64/repodata/repomd.xml: [Errno -1] Gpg Keys not imported, cannot verify repomd.xml for repo blackfire
Trying other mirror.
```

**Comment by tucksaun** [comment]
@arderyp This is not related. GPG key has been changed a couple of months ago: https://blog.blackfire.io/new-gpg-key-2019.html.

**Comment by arderyp** [comment]
Thanks for the heads up @tucksaun, I missed that blog post!
