### ISSUE TITLE
Supported php versions

### ISSUE THREAD

**Issue by scyzoryck** [blackfireio/player#47]
Hey Guys! 
I was looking at the code and I found that based on composer.json file, the library supports php >=5.5.9, but in the code are used php 7.0 features like null coalescing operators. I think we should update version in composer file and use more modern features in the code :). What do you think about it? Should we switch to php 7.0 or some newer version? 

Cheers!

**Comment by lolautruche** [comment]
Hello!

You're right, we should switch to PHP 7.1 at least.
What do you think @romainneutron @fabpot ?

**Comment by romainneutron** [comment]
Hello,
The Blackfire Player supports PHP 5.5 because our customers are using these version. We do not support PHP 5.3 or 5.4 because the guzzle library does not support this.
We should fix the 5.5 support instead.
