### ISSUE TITLE
Regex don't return first match

### ISSUE THREAD

**Issue by dylanngo95** [blackfireio/player#58]
# Step reproduce
## scenario.bkf
```bash
name "Visitor"

endpoint "http://domain.local/"

set login_body '{ "username": "admin@gmail.com", "password": "admin" }'

scenario
    name "Customer login"

    visit url('/rest/V1/integration/customer/token')
        method 'POST'
        header "Content-Type: application/json"
        header "Accept: application/json"
        body login_body
        set token regex('/\\w+/')
        expect status_code() == 200
    visit url('/rest/V1/carts/mine')
        method 'POST'
        header "Content-Type: application/json"
        header "Accept: application/json"
        header "Authorization: Bearer " ~ token
        header "Cookie: PHPSESSID=fki34dvcj80g7ct23m2u80mci9"
        body ''
        set cart_id body()
        expect status_code() == 200
```
## Run command
```bash
blackfire-player run scenario.bkf --variable login_body='{ "username": "admin@gmail.com", "password": "admin" }'
```
## Throw exception
![Screenshot from 2021-03-07 17-07-12](https://user-images.githubusercontent.com/11944757/110236296-94d0c100-7f67-11eb-9dc6-9d0b9bd9991e.png)

## Response for api /rest/V1/integration/customer/token
![Screenshot from 2021-03-07 17-07-49](https://user-images.githubusercontent.com/11944757/110236333-bc278e00-7f67-11eb-9d81-59cb84d70222.png)

Thanks.

**Comment by dylanngo95** [comment]
I'm working on this.
Thanks.

**Comment by jderusse** [comment]
That's the expected behavior, `regexp` takes the text that matched the first captured parenthesized subpattern.

Here is an example from the documentation:
https://blackfire.io/docs/builds-cookbooks/player/index
```
        set token regex('/name="_token" value="([^"]+)"/')
```

**Comment by dylanngo95** [comment]
Hi @jderusse 
How to get token in the response body:
"abc123bdc"
I want to get a token like this: abc123bdc
Thanks.

**Comment by jderusse** [comment]
i guess
```
regex('/(\\w+)/')
```

**Comment by dylanngo95** [comment]
@jderusse 
Thank you.
