### ISSUE TITLE
Authorization with custom token not correct

### ISSUE THREAD

**Issue by tinhnd2** [blackfireio/player#60]
# Validate authorization on header not correct

My custom token like: `531f1b07c466e186a4e3e8193514cc03:wgvqn3h7hbmzyld4rr86i65rt50jje44`

The header like: `Authorization: Bearer 531f1b07c466e186a4e3e8193514cc03:wgvqn3h7hbmzyld4rr86i65rt50jje44`

blackfire-player reponse auth like: `Authorization: Bearer 531f1b07c466e186a4e3e8193514cc03`

I don't login to my API by scenario.
Please help me for fix it ?
Thanks.

**Comment by iamluc** [comment]
Hello,
Could you paste here your scenario?

**Comment by dylanngo95** [comment]
Hi @iamluc 
My scenario like this:
![Screenshot from 2021-03-09 10-36-02](https://user-images.githubusercontent.com/11944757/110414855-594b0980-80c3-11eb-9578-5c8f3c29e874.png)
Thanks.

**Comment by tinhnd2** [comment]
Hi @iamluc 
My scenario is:
![Screenshot from 2021-03-09 10-36-02](https://user-images.githubusercontent.com/79310184/110414995-99aa8780-80c3-11eb-8670-a02af5b8eb1b.png)
Thanks.

**Comment by jderusse** [comment]
This issue should be fixed in new version https://github.com/blackfireio/player/releases/tag/v1.10.1

Could you please give a try @tinhnd2 ?

**Comment by tinhnd2** [comment]
Thank @jderusse 
I have tested it again. It's still correct.
