### ISSUE TITLE
Use variable withing python strings

### ISSUE THREAD

**Issue by thomasdiluccio** [blackfireio/player#61]
I cannot find a way to use variables inside content defined with triple quotes.

This won't work:

```
scenario
    name "Feature"
    visit url('/login')
        set username "fooBar"
        header 'accept: "application/json"'
        method 'POST'
        body
        """
        {
            "username": username,
            "password": "pass"
        }
        """
        expect status_code() == 200
```

Nor something like 

```
<some content>
....
""" ~ variable ~ """
....
<some more content>

```

This may be already possible and, therefore, should be documented.

This is a major drawback when profiling complex applications requiring very large and nested payloads.

**Comment by iamluc** [comment]
Hi,
Indeed this is a missing feature.
A discussion has started in https://github.com/blackfireio/player/pull/54

**Comment by thomasdiluccio** [comment]
Thanks for reaching out. I'm closing this issue as it is already open in #54
