### ISSUE TITLE
[Feature request] Ability to use `var()` wherever we want

### ISSUE THREAD

**Issue by Kocal** [blackfireio/player#67]
Hi!

We have a scenario that should login to our web application (in production) but we don't want to put sensitive information in our `.blackfire.yaml`.

This is what our scenarios file looks like:
```yaml
scenarios: |
    #!blackfire-player

    scenario
        name "Performance regression"

        when env == "prod"
            visit url('/a/super/secret/url')
                auth var('monitoring_username') ~ ':' ~ var('monitoring_password')
                expect status_code() == 200

        visit('/')
            expect status_code() == 200
```

I would expect to run the Blackfire Player with `--variable="monitoring_username=foo" --variable="monitoring_password=bar"`, but instead I have the following issue when validating scenarios:
```
Expression syntax error: The function "var" does not exist around position 1 for expression `var('monitoring_username') ~ ':' ~ var('monitoring_password')`. in .blackfire.yaml
```

Thanks!

**Comment by romainneutron** [comment]
Hello,
The `var` function is only compatible with deprecated yaml scenario.
See this documentation for using variables in bkf format: https://blackfire.io/docs/builds-cookbooks/player#using-variables
