### ISSUE TITLE
It's not possible to specify a custom Content-Type header

### ISSUE THREAD

**Issue by mnocon** [blackfireio/player#75]
Hi!

We're trying to upgrade from Blackfire Player 1.30.0 to 2.3.2 - and the behaviour has changed, our tests that used to pass are now failing with "400 Bad Request" responses.

I believe that there is a bug in the Player - it's no longer possible to specify a custom `Content-Type` header, it is always overwritten to one of three possible values.

### Example API call needing this

In Ibexa DXP we have an API endpoint expecting one of two possible Content-Type header values:
- `application/vnd.ibexa.api.SessionInput+xml`
- `application/vnd.ibexa.api.SessionInput+json`

Doc reference: https://doc.ibexa.co/en/master/api/rest_api/rest_api_reference/rest_api_reference.html#managing-users-create-session-login-a-user

This maps to the following Blackfire Player Scenario:

```
name "Test Content-Type header"

set username ""
set password ""
set basic_auth ""

scenario
    name "Using custom Content-Type header"
    auth basic_auth
    visit url('/api/ibexa/v2/user/sessions')
        method 'POST'
        header "Accept: application/vnd.ibexa.api.Session+json"
        header "Content-Type: application/vnd.ibexa.api.SessionInput+json"
        body
        """i
        {
            "SessionInput": {
                "login": "${username}",
                "password": "${password}"
            }
        }
        """

        expect status_code() == 201
```

I don't have a public environment that I can share with you to use - but I hope it's enough for you.

After this test is executed the tracer option shows the following request:
```
POST /api/ibexa/v2/user/sessions HTTP/1.1
Host: [redacted]
accept: application/vnd.ibexa.api.Session+json
content-type: 
authorization: Basic [redacted]
user-agent: Blackfire PHP Player/1.0
cookie: __blackfire=NO_CACHE
x-blackfire-query: [redacted]
x-blackfire-profile-uuid: [redacted]
{
    "SessionInput": {
        "login": "[redacted]",
        "password": "[redacted]"
    }
}
```

As you can see the `Content-Type` header is empty.

~I think I know the cause of this and will prepare a PR with a possible fix soon.~
My PR with a possible solution: https://github.com/blackfireio/player/pull/76

**Comment by julien-jean** [comment]
Hi @mnocon!

Thanks for reporting the issue. We are going to have a look to your pull request as soon as possible. :+1:

We'll keep you updated!

**Comment by romainneutron** [comment]
Fixed as of https://github.com/blackfireio/player/commit/78390bdd753ca6147e35fc9e4378e3c48da851aa

**Comment by mnocon** [comment]
Thanks!
